language: node_js
node_js:
  - "9"
before_script:
  - npm install
  - cp dist/top-collegue-front/index.html dist/top-collegue-front/404.html
script: npm run build
deploy:
  local-dir: dist/top-collegue-front
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
notifications:
  email: false